# Generated by Django 4.2.2 on 2023-09-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafepayments',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cafepayments',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
    ]
