# Generated by Django 4.2.1 on 2023-05-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beakery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beakery',
            name='image',
            field=models.ImageField(upload_to='images/beakery'),
        ),
    ]
