# Generated by Django 4.1.2 on 2023-07-31 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HukkaOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hukka_offers', to='menu.hukka')),
            ],
        ),
        migrations.CreateModel(
            name='FoodOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_offers', to='menu.food')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink_offers', to='menu.drink')),
            ],
        ),
        migrations.CreateModel(
            name='BeakeryOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beakery_offers', to='menu.beakery')),
            ],
        ),
    ]
