# Generated by Django 4.2.1 on 2023-05-29 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodoffers',
            name='orginal_price',
        ),
        migrations.AddField(
            model_name='foodoffers',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
