# Generated by Django 4.2.2 on 2023-08-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_beakerycategory_bakerycategory'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeakeryOffers',
            new_name='BakeryOffers',
        ),
    ]
