# Generated by Django 4.2.2 on 2023-08-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_rename_beakeryoffers_bakeryoffers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakeryoffers',
            options={'verbose_name': 'Bakery Offer', 'verbose_name_plural': ' Bakery Offer'},
        ),
        migrations.AlterModelOptions(
            name='drinkoffers',
            options={'verbose_name': ' Drink Offer', 'verbose_name_plural': ' Drink Offer'},
        ),
        migrations.AlterModelOptions(
            name='foodoffers',
            options={'verbose_name': ' Food Offer', 'verbose_name_plural': ' Food Offer'},
        ),
        migrations.AlterModelOptions(
            name='hukkaoffers',
            options={'verbose_name': ' Hukka Offer', 'verbose_name_plural': ' Hukka Offer'},
        ),
    ]
