# Generated by Django 4.2.1 on 2023-05-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_remove_foodoffers_orginal_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodoffers',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
