# Generated by Django 4.2.1 on 2023-05-29 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_foodoffers_offer_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodoffers',
            old_name='original_price',
            new_name='price',
        ),
    ]
