# Generated by Django 4.2.1 on 2023-05-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_rename_original_price_foodoffers_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodoffers',
            name='price',
        ),
    ]
