# Generated by Django 4.2.1 on 2023-05-29 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_remove_foodoffers_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodoffers',
            name='offer_price',
        ),
    ]
