# Generated by Django 4.2.1 on 2023-05-29 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_remove_foodoffers_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodoffers',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='foodoffers',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
