# Generated by Django 4.2.1 on 2023-05-29 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
        ('offers', '0007_foodoffers_offer_price_foodoffers_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_rate', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink_offers', to='drinks.drink')),
            ],
        ),
    ]
