# Generated by Django 4.2.2 on 2023-08-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Futsal',
        ),
    ]
