# Generated by Django 4.1.2 on 2023-07-31 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeakeryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HukkaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hukka',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.menuitem')),
                ('image', models.ImageField(upload_to='images/hukka/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.hukkacategory')),
            ],
            bases=('menu.menuitem',),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.menuitem')),
                ('image', models.ImageField(upload_to='images/foods/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.foodcategory')),
            ],
            bases=('menu.menuitem',),
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.menuitem')),
                ('image', models.ImageField(upload_to='images/drinks')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.drinkcategory')),
            ],
            bases=('menu.menuitem',),
        ),
        migrations.CreateModel(
            name='Beakery',
            fields=[
                ('menuitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.menuitem')),
                ('image', models.ImageField(upload_to='images/beakery')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.beakerycategory')),
            ],
            bases=('menu.menuitem',),
        ),
    ]
