# Generated by Django 4.2.2 on 2023-08-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_rename_beakerycategory_bakerycategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bakerycategory',
            options={'verbose_name': 'Bakery Category', 'verbose_name_plural': 'Bakery Category'},
        ),
        migrations.AlterModelOptions(
            name='beakery',
            options={'verbose_name': 'Bakery', 'verbose_name_plural': 'Bakery'},
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={'verbose_name': 'Drink', 'verbose_name_plural': 'Drink'},
        ),
        migrations.AlterModelOptions(
            name='drinkcategory',
            options={'verbose_name': 'Drink Category', 'verbose_name_plural': 'Drink Category'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Food', 'verbose_name_plural': 'Food'},
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Food Category', 'verbose_name_plural': 'Food Category'},
        ),
        migrations.AlterModelOptions(
            name='hukka',
            options={'verbose_name': 'Hukka', 'verbose_name_plural': 'Hukka'},
        ),
        migrations.AlterModelOptions(
            name='hukkacategory',
            options={'verbose_name': 'Hukka Category', 'verbose_name_plural': 'Hukka Category'},
        ),
    ]
