# Generated by Django 4.2.2 on 2023-08-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_bakerycategory_options_alter_beakery_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hukka',
            name='category',
        ),
        migrations.DeleteModel(
            name='HukkaCategory',
        ),
    ]
