# Generated by Django 4.1.2 on 2023-07-31 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.table'),
        ),
    ]
