# Generated by Django 4.2.2 on 2023-08-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_bakerycategory_options_alter_beakery_options_and_more'),
        ('order', '0003_order_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='bakery',
            field=models.ManyToManyField(blank=True, null=True, to='menu.beakery'),
        ),
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.ManyToManyField(blank=True, null=True, to='menu.drink'),
        ),
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(blank=True, null=True, to='menu.food'),
        ),
        migrations.AddField(
            model_name='order',
            name='hukka',
            field=models.ManyToManyField(blank=True, null=True, to='menu.hukka'),
        ),
    ]
