# Generated by Django 4.2.2 on 2023-08-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_bakerycategory_options_alter_beakery_options_and_more'),
        ('order', '0006_hukkaquantity_foodquantity_drinksquantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeryquantity',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.beakery'),
        ),
        migrations.AlterField(
            model_name='drinksquantity',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.drink'),
        ),
        migrations.AlterField(
            model_name='foodquantity',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.food'),
        ),
        migrations.AlterField(
            model_name='hukkaquantity',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.hukka'),
        ),
    ]
