# Generated by Django 4.2.2 on 2023-08-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_bakeryquantity_name_alter_drinksquantity_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakeryquantity',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='drinksquantity',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='foodquantity',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='hukkaquantity',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
