# Generated by Django 4.2.2 on 2023-08-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_bakeryquantity_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bakery',
            field=models.ManyToManyField(blank=True, null=True, to='order.bakeryquantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='drink',
            field=models.ManyToManyField(blank=True, null=True, to='order.drinksquantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(blank=True, null=True, to='order.foodquantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hukka',
            field=models.ManyToManyField(blank=True, null=True, to='order.hukkaquantity'),
        ),
    ]
