# Generated by Django 4.2.2 on 2023-08-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_hukka_category_delete_hukkacategory'),
        ('order', '0010_bakeryquantity_order_drinksquantity_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryquantity',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.beakery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drinksquantity',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.drink'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodquantity',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.food'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hukkaquantity',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.hukka'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='bakery',
            field=models.ManyToManyField(blank=True, through='order.BakeryQuantity', to='menu.beakery'),
        ),
        migrations.AddField(
            model_name='order',
            name='drink',
            field=models.ManyToManyField(blank=True, through='order.DrinksQuantity', to='menu.drink'),
        ),
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(blank=True, through='order.FoodQuantity', to='menu.food'),
        ),
        migrations.AddField(
            model_name='order',
            name='hukka',
            field=models.ManyToManyField(blank=True, through='order.HukkaQuantity', to='menu.hukka'),
        ),
    ]
