# Generated by Django 4.2.2 on 2023-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_bakeryquantity_name_drinksquantity_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
