# Generated by Django 4.2.2 on 2023-09-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_hukka_category_delete_hukkacategory'),
        ('order', '0014_alter_order_total_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BakeryQuantity',
            new_name='BakeryOrder',
        ),
        migrations.RenameModel(
            old_name='DrinksQuantity',
            new_name='DrinkOrder',
        ),
        migrations.RenameModel(
            old_name='FoodQuantity',
            new_name='FoodOrder',
        ),
        migrations.RenameModel(
            old_name='HukkaQuantity',
            new_name='HukkaOrder',
        ),
    ]
